import Head from "next/head";
import Navbar from "../components/NavBar";
import About from "./About";
import HomePage from "./HomePage";
import Pricing from "./Pricing";
import Services from "./Services";
import Notify from "../components/Notify";
import Footer from "../components/Footer";
import Testimonial from "./Testimonial";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Responsive PetCare Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <Navbar />
      <HomePage />
      <About />
      <Services />
      <Pricing />
      <Testimonial />
      <Notify />
      <Footer />
    </div>
  );
}
